"""empty message

Revision ID: 4825b0d132ef
Revises: df6308fbf153
Create Date: 2023-03-23 09:20:48.180590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4825b0d132ef'
down_revision = 'df6308fbf153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('buying_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False)
        batch_op.drop_constraint('purchases_item_id_supplier_id_invoice_number_key', type_='unique')
        batch_op.create_unique_constraint('purchase_unique_constraint', ['item_id', 'supplier_id', 'invoice_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint('purchase_unique_constraint', type_='unique')
        batch_op.create_unique_constraint('purchases_item_id_supplier_id_invoice_number_key', ['item_id', 'supplier_id', 'invoice_number'])
        batch_op.alter_column('buying_price',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
