"""empty message

Revision ID: 66247115c188
Revises: f97d2b694de6
Create Date: 2023-03-22 21:44:28.886525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66247115c188'
down_revision = 'f97d2b694de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PnL',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('credit_amount', sa.Float(), nullable=True),
    sa.Column('debit_amount', sa.Float(), nullable=True),
    sa.Column('credit_account_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('debit_account_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['accounts.id'], ondelete='SET DEFAULT'),
    sa.ForeignKeyConstraint(['debit_account_id'], ['accounts.id'], ondelete='SET DEFAULT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('income_balances')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('buying_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('buying_price',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    op.create_table('income_balances',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('credit_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('debit_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('credit_account_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('debit_account_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['accounts.id'], name='income_balances_credit_account_id_fkey', ondelete='SET DEFAULT'),
    sa.ForeignKeyConstraint(['debit_account_id'], ['accounts.id'], name='income_balances_debit_account_id_fkey', ondelete='SET DEFAULT'),
    sa.PrimaryKeyConstraint('id', name='income_balances_pkey')
    )
    op.drop_table('PnL')
    # ### end Alembic commands ###
