"""empty message

Revision ID: 804326496641
Revises: 89cbc5f01957
Create Date: 2023-03-02 12:12:00.149723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804326496641'
down_revision = '89cbc5f01957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False)
    op.execute("create sequence items_aid_seq start with 100 increment by 2 nocache nocycle")
    op.execute("create sequence customers_aid_seq start with 2000 increment by 5 nocache nocycle")
    op.execute("create sequence suppliers_aid_seq start with 30000 increment by 5 nocache nocycle")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    op.execute(sa.schema.DropSequence(sa.Sequence("items_aid_seq")))
    op.execute(sa.schema.DropSequence(sa.Sequence("customers_aid_seq")))
    op.execute(sa.schema.DropSequence(sa.Sequence("suppliers_aid_seq")))

    # ### end Alembic commands ###
