"""empty message

Revision ID: ec37a13a26fc
Revises: d75cb2256c82
Create Date: 2023-03-22 23:30:12.001672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec37a13a26fc'
down_revision = 'd75cb2256c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PnL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_id', sa.Integer(), nullable=True))
        batch_op.alter_column('credit_account_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('debit_account_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_constraint('PnL_credit_account_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('PnL_debit_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'purchases', ['purchase_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'accounts', ['debit_account_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'accounts', ['credit_account_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('inventory_balances', schema=None) as batch_op:
        batch_op.drop_constraint('inventory_balances_purchase_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'purchases', ['purchase_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('buying_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('buying_price',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('inventory_balances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inventory_balances_purchase_id_fkey', 'purchases', ['purchase_id'], ['id'])

    with op.batch_alter_table('PnL', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('PnL_debit_account_id_fkey', 'accounts', ['debit_account_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key('PnL_credit_account_id_fkey', 'accounts', ['credit_account_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.alter_column('debit_account_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('credit_account_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('purchase_id')

    # ### end Alembic commands ###
