from .users import blp as userblueprint
from .items import blp as itemsblueprint
from .suppliers import blp as supplierblueprint
from .customers import blp as customerblueprint
from .confirmation import blp as confirmationblueprint
from .purchase_accounts import blp as purchaseaccountsblueprint
from .payment_accounts import blp as paymentaccountsblueprint
from .sales_accounts import blp as salesaccountblueprint
from .expense_accounts import blp as expenseaccountingblueprint
from .invoice_resource import invoices_bp as invoiceblueprint
from .receipt_resource import receipt_bp as receiptblueprint