"""empty message

Revision ID: 838870306265
Revises: 7c339e0ec87b
Create Date: 2023-01-20 20:04:44.435043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838870306265'
down_revision = '7c339e0ec87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_unarchived', sa.DateTime(), nullable=True))

    with op.batch_alter_table('item_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_unarchived', sa.DateTime(), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_unarchived', sa.DateTime(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_unarchived', sa.DateTime(), nullable=True))

    with op.batch_alter_table('supplier_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_unarchived', sa.DateTime(), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_unarchived', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_unarchived', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_unarchived')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('date_unarchived')

    with op.batch_alter_table('supplier_account', schema=None) as batch_op:
        batch_op.drop_column('date_unarchived')

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_column('date_unarchived')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('date_unarchived')

    with op.batch_alter_table('item_account', schema=None) as batch_op:
        batch_op.drop_column('date_unarchived')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('date_unarchived')

    # ### end Alembic commands ###
