"""empty message

Revision ID: 86df326dfb3c
Revises: 07a4435c884c
Create Date: 2023-01-21 03:35:28.474368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86df326dfb3c'
down_revision = '07a4435c884c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.drop_constraint('items_item_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_unique_constraint('items_item_number_key', ['item_number'])
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
