"""empty message

Revision ID: 4a09b4e130fc
Revises: ad179f73bd92
Create Date: 2023-04-19 18:54:28.660219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a09b4e130fc'
down_revision = 'ad179f73bd92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier payment accounting')
    op.drop_table('supplier balances')
    op.drop_table('inventory balances')
    op.drop_table('customer payment accounting')
    op.drop_table('customer payments')
    op.drop_table('payments')
    op.drop_table('sales accounting')
    op.drop_table('purchase accounting')
    op.drop_table('customer balances')
    with op.batch_alter_table('bank_balances', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('buying_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False)
        batch_op.alter_column('item_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.alter_column('lines_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('selling_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False)
        batch_op.alter_column('item_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False)

    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('item_cost',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('selling_price',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('lines_cost',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('item_cost',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('buying_price',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('bank_balances', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    op.create_table('customer balances',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"customer balances_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('receipt_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receipt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='customer balances_customer_id_fkey'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], name='customer balances_receipt_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customer balances_pkey'),
    sa.UniqueConstraint('receipt_id', 'currency', 'customer_id', name='customer balances_receipt_id_currency_customer_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('purchase accounting',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('credit_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('debit_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('credit_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('debit_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['credit_account_id'], ['accounts.id'], name='purchase accounting_credit_account_id_fkey'),
    sa.ForeignKeyConstraint(['debit_account_id'], ['accounts.id'], name='purchase accounting_debit_account_id_fkey'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='purchase accounting_invoice_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='purchase accounting_pkey')
    )
    op.create_table('sales accounting',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('credit_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('debit_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('credit_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('debit_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['credit_account_id'], ['accounts.id'], name='sales accounting_credit_account_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['debit_account_id'], ['accounts.id'], name='sales accounting_debit_account_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], name='sales accounting_receipt_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sales accounting_pkey'),
    sa.UniqueConstraint('receipt_id', name='sales accounting_receipt_id_key')
    )
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('payments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('transaction_number', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('payment_description', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payment_status', postgresql.ENUM('not_paid', 'fully_paid', 'partially_paid', 'over_paid', name='payment_status'), autoincrement=False, nullable=False),
    sa.Column('pay_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='payments_invoice_id_fkey'),
    sa.ForeignKeyConstraint(['pay_account_id'], ['accounts.id'], name='payments_pay_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey'),
    sa.UniqueConstraint('transaction_number', name='payments_transaction_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('customer payments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"customer payments_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('transaction_number', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('payment_description', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payment_status', postgresql.ENUM('not_paid', 'fully_paid', 'partially_paid', 'over_paid', name='payment_status'), autoincrement=False, nullable=False),
    sa.Column('receive_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receipt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], name='customer payments_receipt_id_fkey'),
    sa.ForeignKeyConstraint(['receive_account_id'], ['accounts.id'], name='customer payments_receive_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customer payments_pkey'),
    sa.UniqueConstraint('transaction_number', name='customer payments_transaction_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('customer payment accounting',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('credit_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('debit_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('credit_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('debit_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['balance_id'], ['customer balances.id'], name='customer payment accounting_balance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credit_account_id'], ['accounts.id'], name='customer payment accounting_credit_account_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['debit_account_id'], ['accounts.id'], name='customer payment accounting_debit_account_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['customer payments.id'], name='customer payment accounting_payment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='customer payment accounting_pkey')
    )
    op.create_table('inventory balances',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"inventory balances_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sales_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='inventory balances_invoice_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='inventory balances_item_id_fkey'),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], name='inventory balances_sales_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='inventory balances_pkey'),
    sa.UniqueConstraint('item_id', 'invoice_id', name='inventory balances_item_id_invoice_id_key')
    )
    op.create_table('supplier balances',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"supplier balances_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('invoice_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='supplier balances_invoice_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='supplier balances_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='supplier balances_pkey'),
    sa.UniqueConstraint('supplier_id', 'currency', 'invoice_id', name='supplier balances_supplier_id_currency_invoice_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('supplier payment accounting',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('credit_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('debit_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('credit_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('debit_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['balance_id'], ['supplier balances.id'], name='supplier payment accounting_balance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credit_account_id'], ['accounts.id'], name='supplier payment accounting_credit_account_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['debit_account_id'], ['accounts.id'], name='supplier payment accounting_debit_account_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name='supplier payment accounting_payment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='supplier payment accounting_pkey')
    )
    # ### end Alembic commands ###
